export const FETCH_RECIPES_REQUEST = "FETCH_RECIPES_REQUEST";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE";

export const SELECT_RECIPE = "SELECT_RECIPE";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const UPDATE_RECIPE_ORDER = "UPDATE_RECIPE_ORDER";
